### ISSUE TITLE
the coco link

### ISSUE THREAD

**Issue by SHITIANYU-hue** [ma-labo/PromptCharm#4]
hi author, thanks for your outstanding work, it seems this is not opensourced: git clone -b penguin https://github.com/paulwong16/ecco.git

may i know if you could release the link? thanks!

**Comment by paulwong16** [comment]
Thanks for your interest!

I have updated the link. Can you try again? 

Please try with `git clone -b promptcharm https://github.com/paulwong16/ecco.git`

**Comment by SHITIANYU-hue** [comment]
Yes，thanks！
